- R/theme-preview.R
- inst/themer/themer.scss
> Make themer UI collapsible

- R/theme-preview.R
- R/utils.R
- inst/themer/options.json
- tests/testthat/test-bs-theme.R
Install `remotes::install_github("rstudio/bootstraplib")`, then run the following:
```r
bs_theme_new()
```
Check that:
* Theme customizer can be dragged
* Theme customizer can be collapsed by clicking on caret
* Changing colors/options prints all changed values to the console
* After changes values, exit the app, copy/paste the most recent code into your console (and press enter), then run `bs_theme_preview()` again. This time, the UI should reflect changes you made previously (on startup).
> Refactor theming UI to reflect new functions

- DESCRIPTION
- R/bs_sass.R
- man/bootstrap.Rd
Requires https://github.com/rstudio/sass/pull/48
> Leverage the new sass::output_file()

- .Rbuildignore
- .gitattributes
- .github/workflows/R-CMD-check.yaml
This is to fix issues with tests on Windows.
> Better method for ensuring LF consistency

- R/bs_sass.R
- R/layers.R
- tests/testthat/test-utils.R
> Do not execute the js map file

- R/bs-dependencies.R
- tests/testthat/test-theme-version.R
> Make sure bs_theme_dependencies() retrieves HTML dependencies from theme

- .Rbuildignore
- .github/PULL_REQUEST_TEMPLATE.md
- .github/bug_report.md
- .github/question.md
- DESCRIPTION
- LICENSE
- R/bs-dependencies.R
- R/bs-global.R
- R/bs-theme-layers.R
- R/bs-theme-preview.R
- R/bs-theme.R
- R/files.R
- R/precompiled.R
- R/utils.R
- README.Rmd
- README.md
- _pkgdown.yml
- inst/bs3compat/_wells.scss
- inst/package.json
- inst/themer-demo/app.R
- man/bs_bundle.Rd
- man/bs_theme.Rd
- tests/testthat.R
- tests/testthat/test-zzz-precompile.R
- tools/bs3_theme_base_colors.R
- tools/main.R
- tools/yarn_install.R
- vignettes/theming.Rmd
Renames the package from `{bootstraplib}` to `{bslib}`
Make sure to rename the repo after merging this!
> Rename package to bslib, closes #128

- R/bs-dependencies.R
- man/bs_dependency.Rd
Needed for https://github.com/rstudio/shiny/pull/3155
> Properly support script in .dep_args of bs_dependency()

- inst/lib/bootswatch/dist/sketchy/_bootswatch.scss
- tools/patches/008-bootswatch-sketchy-form-positioning.patch
> Make sketchy's position:relative on radio/checkbox inputs important

- inst/lib/bootswatch/dist/materia/_bootswatch.scss
- inst/lib/bootswatch/dist/materia/_variables.scss
- tools/patches/006-bootswatch-materia.patch
This should've been done in #155, but I forgot about it. 
See #193 (and #148) for examples & screenshots.
> Patch materia theme to make box-shadows more themable

- .github/workflows/R-CMD-check.yaml
- .github/workflows/pkgdown.yaml
- .gitignore
Try to address running out of requests when using remotes. Now use `pak` to address this.
Related: https://github.com/rstudio/shiny/pull/3230
----------------------
- [NA] Add unit tests in the tests/testthat directory.
- [NA] This project uses [roxygen2 for documentation](http://r-pkgs.had.co.nz/man.html). If you've made changes to documentation, run `devtools::document()`.
- [NA] Ensure your code changes follow the style outlined in http://r-pkgs.had.co.nz/style.html
- [NA] Add an entry to NEWS.md concisely describing what you changed.
> Update GHA to use `pak`

- .github/workflows/R-CMD-check.yaml
https://github.com/rstudio/bslib/pull/206/commits/e514a872fe8ed1541d4ca6f96c2eaf8333e2cdb5 shows that the demo app can be deployed
-------------------
> Fix bslib deployment

- .github/workflows/R-CMD-check.yaml
- .github/workflows/pkgdown.yaml
Related: https://github.com/rstudio/bslib/pull/206/files#diff-9c940e8ad2b7bc4c26ec3da57b94bc00e73e2166cfed689da51a4c59bcc0a310R132
Related: https://github.com/rstudio/bslib/pull/206/files#diff-9c940e8ad2b7bc4c26ec3da57b94bc00e73e2166cfed689da51a4c59bcc0a310R138
> Use ubuntu for extra GHA workflows

- DESCRIPTION
> 0.2.4 release candidate

- R/bs-theme-preview.R
> Overlay BS4 spinner while Sass is compiling

- DESCRIPTION
- inst/themer-demo/app.R
Fixes https://github.com/rstudio/bslib/issues/257
> Add UI element to plots page if thematic is not installed.

- DESCRIPTION
- R/bs-current-theme.R
- R/bs-dependencies.R
- R/bs-theme-preview.R
- R/onLoad.R
> bs_current_theme() no longer causes shiny to be loaded

- .github/workflows/pkgdown.yaml
> Install renv in pkgdown workflow

- R/bs-theme-preview.R
> Improve bs_themer()'s spinner/blur effect

- .Rbuildignore
- .gitignore
- DESCRIPTION
- NEWS.md
- README.Rmd
- README.md
- man/bs_theme_dependencies.Rd
> v0.2.5 release candidate

- NEWS.md
- R/bs-theme.R
- inst/bs3compat/js/transition.js
> Legacy support for .nav .fade transitions

- R/nav-update.R
- R/navs-legacy.R
Closes https://github.com/rstudio/shinycoreci-apps/issues/149
> Fix typos in nav logic

- R/bs-current-theme.R
- R/bs-dependencies.R
- R/bs-theme.R
- R/onLoad.R
- R/utils.R
> Throw version=5 only when dependencies are requested and shiny is loaded

- DESCRIPTION
- NEWS.md
- R/navs-legacy.R
- man/bs_theme.Rd
> BS5 renamed sr-only to visually-hidden

- DESCRIPTION
> Require the most recent version of memoise

- R/card.R
- R/value-box.R
> Better overflow defaults for card() and value_box(showcase)

- R/card.R
- R/navs.R
- inst/components/card.scss
- man/card_body.Rd
- man/value_box.Rd
- vignettes/cards.Rmd
Best reviewed commit by commit
Probably worth adding some more targeted unit tests
> Various card() improvements

- R/bs-theme-preset-builtin.R
- inst/builtin/bs5/shiny/_mixins.scss
- inst/builtin/bs5/shiny/_rules.scss
- inst/builtin/bs5/shiny/_variables.scss
For #625 
Uses more SASS variables in more places. Also uses SASS variables from `selectize.scss` to set the dropdown colors.
> Use more sass in the shiny sass files

- _pkgdown.yml
Follow up to #662 (should fix the website workflow)
> Add tooltip() to pkgdown reference

- inst/builtin/bs5/shiny/ionrangeslider/_rules.scss
> feat(shiny-preset): Left-align and style slider animate button

- NEWS.md
> Add PR link in news entry

- R/staticimports.R
Brings in updates:
- https://github.com/wch/staticimports/pull/26
- https://github.com/wch/staticimports/pull/22
> chore: Update static imports

- .github/workflows/R-CMD-check.yaml
Another attempt at fixing deployment of examples
> Downgrade version of rsconnect

- inst/themer/options.json
> fix(themer): fix invalid options.json

- inst/lib/bs5/scss/_variables.scss
- tools/patches/021-add-navbar-bg-vars-bs5.patch
> Fix mistake in navbar-dark-contrast's default value

- NEWS.md
Apologies for not including this in the original PR
> docs: Add news item for #775

- tests/testthat/_snaps/bs-theme-preset-builtin.md
- tests/testthat/_snaps/bs-theme-preset.md
testthat 3.2 updated the error snapshot styles
> tests: Update snaps for testthat 3.2

- inst/lib/bsw5/dist/cyborg/_bootswatch.scss
- inst/lib/bsw5/dist/cyborg/_variables.scss
- inst/lib/bsw5/dist/darkly/_bootswatch.scss
- inst/lib/bsw5/dist/darkly/_variables.scss
- inst/lib/bsw5/dist/slate/_bootswatch.scss
- inst/lib/bsw5/dist/slate/_variables.scss
- inst/lib/bsw5/dist/solar/_bootswatch.scss
- inst/lib/bsw5/dist/solar/_variables.scss
- inst/lib/bsw5/dist/superhero/_bootswatch.scss
- inst/lib/bsw5/dist/superhero/_variables.scss
- inst/lib/bsw5/dist/vapor/_variables.scss
- tools/patches/032-bootswatch-emphasis-color.patch
> Fix emphasis-color issues for dark Bootswatch themes

- R/page.R
- R/utils-deps.R
> Don't include component dependencies in a legacy context

- NEWS.md
- inst/examples-shiny/card/app.R
Update NEWS in preparation for release.
Also updates `inst/examples-shiny/card/app.R` in response to changes in `card_image()` to keep its behavior consistent (we use it for testing)
> Update news; update example app in response to card_image() changes

- NEWS.md
- R/input-dark-mode.R
- R/input-switch.R
> feat: Enable bookmarking in `input_switch()` and `input_dark_mode()`

- README.Rmd
- README.md
> Remove duplicate title header on readme

- R/bs-theme-preset-brand.R
- tests/testthat/test-bs-theme-preset-brand.R
> Brand: Support typography font family shortcuts

- vignettes/brand-yml/index.Rmd
> typo in brand vignette
