rstudio/bslib

R/theme-preview.R, inst/themer/themer.js, inst/themer/themer.scss
A few non-obvious edge case behaviors to note:
1. When the window is resized, the theme customization UI should stay the same distance from its closest corner
2. The theme customization UI cannot be moved beyond the edge of the browser window
3. The collapse animation moves toward the nearest edge (but the caret always points down to expand, up to collapse; you could argue for it changing to point to the nearest edge, though I suspect it would be more confusing to see the arrow direction change simply from dragging past the middle of the screen)
4. On browsers that support it (unfortunately not RStudio desktop, at least on Linux) dragging operations should continue even if the cursor moves outside the browser
=> Implement dragging of theme customization UI

R/theme-preview.R, man/run_with_themer.Rd
```r
```
Now enter `*` into any of the font input boxes (in the interactive themer). The app will crash with:
```r
Error: Invalid CSS after "$font-family-base:": expected expression (e.g. 1px, bold), was "* !default;"
on line 1:19 of stdin
>> $font-family-base: * !default;
```
This change ensures that `sass()` compilation won't crash the app, but an informative warning is still thrown
=> More graceful handling of user input that leads to sass() compilation errors

R/theme-preview.R, inst/themer/disable-bootstrap.js
```r
```
Disable the "rounded corners" option. Notice how the well and pills still have rounded corners. The reason is that with `$enable-rounded: false`, `border-radius` isn't defined; however, since the initial Bootstrap CSS is built with `$enable-rounded: true`, the rules from the initial build still apply
=> Have themer try it's best to disable the initial bootstrap stylesheet

R/theme-preview.R
```r
```
Enter `*` into any of the font input boxes. Modifying other inputs has no effect (because sass compilation still fails). Although the error is log to the R console, it may not be obvious to the user why changes aren't taking effect.
This addresses the issue by displaying a notification in the app when compilation is failing.
=> Inform user about realtime sass compilation errors

R/theme-preview.R
```r
bs_theme_new()
bs_theme_base_colors(bg = "#444", fg = "#e4e4e4")
```
Change the background color to a darker color. Note how the text doesn't contrast appropriately
=> If fg/bg hasn't changed, themer should fallback to vals named black/whit

R/bs_sass.R
It seems safer to throw warnings and allow users to decide what they want to do (someday we may want to `write_attachments=T` when compiling CSS for Shiny inputs, for instance)
=> Don't force write_attachments = F in bootstrap_sass()

DESCRIPTION, R/bs_sass.R, R/layers.R, R/theme-preview.R, R/utils.R, man/bootstrap.Rd
This PR does the following:
* When the inputs are the same, it uses the same output directory every time. If the output directory already exists, it won't bother writing files there.
* Adds a wrapper function `system_file()`, which is faster than `system.file`. (The latter was a bottleneck.)
Before the `system_file` change:
```
> system.time(bootstrap())
user  system elapsed 
0.403   0.038   0.441 
> system.time(bootstrap())
user  system elapsed 
0.034   0.009   0.043
```
After:
```
> system.time(bootstrap())
user  system elapsed 
0.385   0.032   0.416 
> system.time(bootstrap())
user  system elapsed 
0.010   0.003   0.013 
```
This should be merged after https://github.com/rstudio/sass/pull/44. (The `Remotes` field here will have to be updated after that PR is merged.)
*****
Testing …
=> Use consistent output directory for bootstrap()

R/bs_sass.R, README.Rmd
Closes #83.
The issue here is that we want to include
```html
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
```
with Bootstrap, but we're currently generating:
```r
dep <- htmlDependency(
"foo", "1.0", src = c(href = "/"), 
meta = c(	        
name = "viewport",	
content = "width=device-width, initial-scale=1, shrink-to-fit=no"	
)
)
renderDependencies(list(dep), "href")
```
```html
<meta name="name" content="viewport" />
<meta name="content" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
```
This fixes that problem
=> Fix bootstrap()'s meta viewport tag

inst/bs3compat/_shiny_input.scss, inst/lib/.yarn-integrity, tests/testthat/test-bs4-deps.R
Gets rid of LibSass warnings thrown in unit tests
=> Sass warnings

R/bs-theme.R
Ref: https://github.com/rstudio/bslib/pull/160#discussion_r524554344
> No, this is intentional so that you can do `bs_remove(bs_theme(), "bootswatch")` and have it work regardless of the theme
Then it should be static with no walrus sign.
=> Remove rlang walrus for static key

R/bs-theme.R, tests/testthat/test-theme-update.R
Follow up to #173, which introduced this new bug (and adds a test to make sure it's fixed)
```r
> sass::sass(bs_theme_update(bs_theme(), bootswatch = "cyborg"))
Error in compile_data(as_sass(input), options) : 
Error: argument `$color` of `rgba($color, $alpha)` must be a color
on line 67:33 of inst/lib/bootswatch/dist/cyborg/_variables.scss, in function `rgba`
from line 67:33 of inst/lib/bootswatch/dist/cyborg/_variables.scss
from line 7:9 of stdin
>> $table-accent-bg:               rgba($contrast-bg, .05) !default;
--------------------------------^
```
=> Make sure color-contrast() is defined before Bootswatch variables on update

R/bs-theme-update.R
Follow up to https://github.com/rstudio/htmltools/pull/194
=> htmltools::parseCssColors now requires character vector input

R/bs-theme-update.R, inst/lib/bootswatch/dist/solar/_variables.scss, inst/sass-utils/color-contrast.scss
Provides a fix for `bs_theme_preview(bs_theme(bootswatch = "solar"))`
=> Proper scoping of color contrasting parameters

inst/themer-demo/global.R
The code in the `?geom_errorbar` example is:
```R
dodge <- position_dodge(width=0.9)
p +
geom_col(position = dodge) +
geom_errorbar(aes(ymin = lower, ymax = upper), position = dodge, width = 0.25)
```
This PR makes the code in the themer demo more like the code in the ggplot example.
Before:
After:
=> Fix dodging for GeomErrorBar example

R/fonts.R
This PR addresses this comment from CRAN:
```
Also, checking creates and leaves behind
~/.cache/R-bslib
in violation of the CRAN Policy's
Packages should not write in the user's home filespace (including
clipboards), nor anywhere else on the file system apart from the R
session's temporary directory (or during installation in the location
pointed to by TMPDIR: and such usage should be cleaned up). Installing
into the system's R installation (e.g., scripts to its bin directory)
is not allowed.
Limited exceptions may be allowed in interactive sessions if the
package obtains confirmation from the user.
For R version 4.0 or later (hence a version dependency is required or
only conditional use is possible), packages may store user-specific
data, configuration and cache files in their …
```
=> Use `tools::R_user_dir()` when possible

vignettes/bs4-variables.Rmd
Before the sass variables table would always be 90% of the available viewport wide. This is good until you're working on a super-wide display and the table is out-of-control. Now we max its width at `1300px` which lets all columns be seen.
=> made sure table doesn't just grow to huge on ultra-wide displays

R/bs-theme-preview.R
Needed for the theming widget to appear over the navbar in https://github.com/rstudio/flexdashboard/pull/305
=> Bump bs_themer() z-index from 1000 to 1059

R/bs-global.R, R/utils.R
And recommend using `session$setCurrentTheme()` instead. The intention is to avoid confusion when trying to do something like:
````
---
runtime: shiny
output: 
html_document:
theme:
version: 4
---
```{r}
bslib::bs_global_theme_update(bg = "black", fg = "white", primary = "purple")
```
```{r}
sliderInput("foo", "bar", 1, 3, 2)
```
````
Which works as expected without `runtime: shiny`, but inside of a shiny runtime, the more proper way to do this is to do this instead
````
---
runtime: shiny
output: 
html_document:
theme:
version: 4
---
```{r, include=FALSE}
session$setCurrentTheme(bslib::bs_theme(bg = "black", fg = "white", primary = "purple"))
```
```{r}
sliderInput("foo", "bar", 1, 3, 2)
```
````
=> Emit warning when bs_global_set() is called inside runtime: shiny 

R/bs-theme.R, tests/testthat/test-theme-bootswatch.R
Will be useful for https://github.com/rstudio/flexdashboard/pull/327, which wants to use Bootswatch cosmo by default
=> Allow for bootswatch='default' in bs_theme()

R/bs-theme-preview.R, _pkgdown.yml
Closes #321. Introduced by #312 (now when in devmode, source maps are included and the existing `bs_get_contrast()` algorithm doesn't account for that).
=> Fix bs_get_contrast() when in shiny devmode

tests/testthat/test-theme-base-colors.R
We are planning a breaking change to the condition expectations in testthat release (see NEWS item in https://github.com/r-lib/testthat/pull/1401). This PR implements a preventive fix that works with and without the breaking change.
There is no hurry to get this fix on CRAN since we are skipping one released version of testthat before going through with the change.
=> Fix condition expectations in prevision of testthat breaking change

inst/bs3compat/js/bs3compat.js
In #304, I changed the overall approach to shimming Bootstrap's `$.fn.tab` jQuery plugin (I wanted to move away from assuming that it exists), but that approach won't work when tabs are shown programmatically (e.g., `shinycoreci-apps/apps/213-tab-panels`). 
This reverts it to use the same `.noConflict()` approach we were using before in a way that works for Bootstrap 5. Originally, I thought that this approach wasn't going to work at all because Bootstrap 5 doesn't register this plugin until the DOM is ready, but now that we execute this code after the DOM is ready, this approach seems to work fine.
=> Revert to pre-Bootstrap 5 nav bs3compat shimming

NEWS.md, R/navs-legacy.R
Closes #423
First run the following app. Note that if you click "B" (to show "b"), you can't click "Menu" -> "A" (to show "a")
```r
library(shiny)
library(bslib)
ui <- navbarPage(
theme = bs_theme(version = 5),
title = "reprex",
navbarMenu("Menu", tabPanel("A", "a")),
tabPanel("B", "b")
)
shinyApp(ui, function(...) {})
```
Now install `remotes::install_github("rstudio/bslib")` and re-run the app. Verify that you're able to click "B"  (to show "b") and then click "Menu" -> "A" (to show "a")
=> More carefully mark nav_menu() as active across Bootstrap versions

R/card.R
Closes #469
The crux of the issue is that (at least currently) `insertUI()` runs through jQuery's `.html()` which executes `<script>` tag in the head of document.
=> Make `card()` JS more robust against where the `<script>` is executing

R/sidebar.R, man/sidebar.Rd
This is prequel to a series of sidebar-related PRs. Mostly, this PR adjusts the code style of the function signatures of `layout_sidebar()` and `sidebar()` so arguments appear on their own line, which will reduce merge conflicts and dependences between the rest of the PRs I'm extracting from #516.
=> Adjust sidebar function signature and require `sidebar` argument

inst/components/sidebar.scss
A small follow up to #517 to fix a change in selector name in the scss.
=> Fix scss for `sidebar(open="desktop")`

vignettes/sidebars.Rmd
Small edit to sidebars article to remove unnecessary fenced div markers
=> Remove extra fenced div delimiters

R/sidebar.R, inst/components/sidebar.scss
Fixes #551
The biggest part of this PR is that we now use CSS variables to set the sidebar background color. We add `--bslib-sidebar-bg` and `--bslib-sidebar-fg` by default to `.bsib-sidebar-layout`. Both `> .sidebar` and `> .collapse-toggle` will pick up their background color from these CSS variables. This means that the sidebar and toggle colors can be set with one rule applied to `.bslib-sidebar-layout`.
Internally, when `bg` or `fg` are set in `sidebar()`, we now pass that information up to `layout_sidebar()` and set those CSS variables in a `style` argument for that specific layout.
The other change made here is to choose a default sidebar color that more closely matches the typical card-header background and that will be appropriately dark when used in a dark theme. Previously we …
=> Sidebar color CSS vars and defaults

DESCRIPTION
Seems like plotly might need to be listed in deploys (since several of the deployed apps use it)? Won't actually know if this fixes deploys until we merge 
https://github.com/rstudio/bslib/actions/runs/4949243116/jobs/8851386492#step:6:34
=> Attempt to fix deploys

R/deprecated.R
There was a small bug in #546 that would manifest when running an app via `shiny::runApp()`.
When the following app is run via `shiny::runApp()`
```r
library(shiny)
library(bslib)
ui <- fluidPage(
navs_bar(nav("Foo", "foo"))
)
shinyApp(ui, function(...) { })
```
it will currently generate an error
```
Error in `rlang::env_name()`:
! `env` must be an environment, not `NULL`.
```
due to `runApp()`'s use of `eval()`. This PR catches the case of the calling function's environment being `NULL` and assumes that means the function is not being called from within Shiny. With this PR, when you exit the app, the expected deprecation warnings are printed.
You can replace `navs_bar()` with `tabsetPanel()` to verify that the deprecation warnings are appropriately muffled in `tabsetPanel()`.
```r …
```
=> Fix `NULL` caller function environment

inst/themer-demo/app.R
In https://github.com/rstudio/bslib/pull/572/files, we switched from `navbarPage()` to `page_navbar()`, which changed the default `inverse` from `F` to `T`. This changes it back to `F` so that we don't have to change/update `301` or `302` tests https://rstudio.github.io/shinycoreci/results/2023/05/18/
=> Have themer-demo continue to default to inverse = FALSE

vignettes/theming.Rmd
Link to [fontpair](fontpair.co) was broken. Fixed now, but maybe best to use the root as the site's Pairings tab is easily found.
=> Update link to fontpair.co in theming article

R/bs-theme-preset.R, R/bs-theme.R, man/bs_global_theme.Rd, man/bs_theme.Rd, tests/testthat/_snaps/bs-theme-preset.md, tests/testthat/test-bs-theme-preset.R
In #629, we added a new `name` argument to replace the `bootswatch` argument. Eventually, in that PR, I settled into a "preset" as the name for a "starter theme", i.e. a _preset_ covers Bootswatch themes and themes provided by bslib.
This PR renames `name` in `bs_theme()` to `preset`, which is more descriptive and has clearer intent, especially when we start using the word _preset_ more often in our documentation.
=> feat!(bs_theme): Rename `preset` from `name`

NEWS.md, R/accordion.R
=> Don't call `shiny::restoreInput()` inside `accordion()` if id isn't provided

yarn.lock
Updates `yarn.lock` to find the correct reference for
```
"@types/rstudio-shiny": "https://github.com/rstudio/shiny#v1.7.4",
```
The goal is to fix errors seen in CI, e.g. https://github.com/rstudio/bslib/actions/runs/5426683169/jobs/9947977664
FYI, this was a surgical update: I removed `@types/rstudio-shiny` from the lockfile and from `node_modules/` and then ran `yarn install`.
=> Update `@types/rstudio-shiny` in `yarn.lock`

inst/builtin/bs5/shiny/_rules.scss, inst/builtin/bs5/shiny/_variables.scss
* Make only the default `actionButton()` the outline variant, keeping `btn-primary` and friends the solid variant.
* Update the gray color values.
* Use `$gray-600` instead of `$red` for `$form-text-color`
=> Shiny preset theme review and updates

R/value-box.R
Closes #666. Follow up to #664.
=> Make sure value_box()'s dependency doesn't create an empty card-body (i.e., card item)

inst/themer-demo/app.R
Currently, if you use `bs_theme_preview()` with BS version < 5, the app fails to load due to `layout_column_wrap()` requiring Bootstrap 5 (that's just the first BS5 requirement).
```r
bs_theme(4) |> bs_theme_preview()
```
This PR adds a version check and only includes the dashboard page if the theme is BS5+.
=> fix(bs_theme_preview): Don't include dashboard tab for BS < 5

inst/themer-demo/app.R
Adds a few more tables and table features to the `bs_theme_preview()` app:
1. I added tabs under the Tables page with DataTables and Bootstrap (tables)
2. The DataTables example updates:
* Now uses more features – added filters and a caption. Filters use factors and numeric values.
* Uses `style="auto"` rather than defaulting to `"bootstrap4"` 
* See rstudio/DT#1074 for improved auto style support
3. The Bootstrap tabs include plain tables, striped tables and tables with hover accents.
=> feat(bs_theme_preview): Add more DT features and more tables

R/utils-deps.R
Follow up to #677, which introduced the following error
```r
shiny::devmode(FALSE)
bslib::card()
#> Error: `bundle` must be a `sass_bundle()` object.
```
=> Fallback to default theme if none is detected

NEWS.md, R/bs-theme-preset-bootswatch.R
While looking into #684, I noticed that we have some style spillover between `.btn-default` and `.btn-light`. We were essentially causing some of the `.btn-secondary` styles that we're extending to `.btn-default` to be applied to `.btn-light` as well.
=> fix(bootswatch): Exclude `.btn-light` from `.btn-default` extension of `.btn-secondary`

.github/workflows/lock-threads.yaml
Adds rstudio/shiny-workflows#20 to lock closed issues that haven't had activity in the last 60 days. This workflow would run once per week (early Monday morning) to lock inactive issues (or manually with a workflow dispatch).
There are [currently 216 such issues in bslib](https://github.com/search?q=repo:rstudio/bslib+is:closed+is:unlocked+updated:%3C2023-04-15&type=issues) that would be locked. The action will handle 50 at a time to avoid rate-limiting issues.
=> ci(lock-threads): Automatically lock closed, inactive issues

inst/builtin/bs5/shiny/ionrangeslider/_rules.scss, inst/builtin/bs5/shiny/ionrangeslider/_variables.scss
Fixes #691
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://github.com/rstudio/bslib/assets/5420529/a911068f-351c-4ebe-8e48-815144ad55e1" alt="image" height="200">
=> fix(shiny-preset): Adjust slider handle size and position to better center on line and bar

inst/examples/card/deploy.R, inst/examples/flights/deploy.R, inst/examples/value_box/deploy.R, inst/themer-demo/deploy.R
This is a bit of a guess, but we might need to include `forceUpdate = TRUE` to signal that we're expecting these apps to already exist. It's possible that this previously worked non-interactively and/or was changed with recent updates in the rsconnect package.
(Although the workflow seems to [be failing intermittently](https://github.com/rstudio/bslib/actions/workflows/R-CMD-check.yaml?query=branch:main+is:success))
The [typical error we see](https://github.com/rstudio/bslib/actions/runs/5669160858/job/15361771692) in our shinyapps deployment failures is this error:
```
✔ Deploying "themer-demo" to "server: shinyapps.io / username: ***"
ℹ Creating application on server...
Error in `POST()`:
! <https://api.shinyapps.io/v1/applications/> failed with HTTP status 409
Application exists with …
```
=> ci(examples): Fix shinyapps.io deployment

.github/workflows/R-CMD-check.yaml
Looks like we're running into this issue https://community.rstudio.com/t/unable-to-deploy-on-shinyapp-io/170160
Instead of downgrading `{rsconnect}`, this'll upgrade to the dev version.
=> Another attempt at fixing deploys

inst/builtin/bs5/shiny/tables/_rules.scss
=> feat(shiny-preset): Restore "showing X of Y entries" in small datatables

NEWS.md, R/layout.R
Fixes #727 
Background in this CSS tricks article: [Preventing a Grid Blowout](https://css-tricks.com/preventing-a-grid-blowout/)
Using `minmax(0, 1fr)` constrains each column to use up to `1fr`, otherwise the intrinsic width of one column can affect the sizes of other columns. (See the example in https://github.com/rstudio/bslib/issues/727#issuecomment-1666172356)
https://github.com/rstudio/bslib/assets/5420529/1408866f-2166-4680-b5b5-d7c1c829e9c3
=> fix(layout_columns): Use `minmax(0, 1fr)` for column widths

NEWS.md, R/bs-theme-preview.R, inst/themer/options.json, inst/themer/themer.js
Adds a "Preview dark mode" toggle to the theme previewer. This only toggles the dark mode on the page – in the future we may want to add more support for updating dark mode colors, but that isn't part of this PR. 
I added a tooltip with info about the dark mode feature, where I tried to word the tip text to indicate that the colors in the customization menu are still for light mode.
https://github.com/rstudio/bslib/assets/5420529/de1a52fe-a3f4-4f0e-9f17-aeb3c9142f30
- I added a new `switch` input control type to the themer controls.
- The `options.json` can now communicate minimum Bootstrap versions for input controls. The dark mode switch gets `"version": {"min": 5}`.
- Thought for the future: the `options.json` might be able to encode more things, like which inputs directly correspond …
=> feat(bs_theme_preview): Add dark mode preview toggle

pkgdown/extra.scss
Fixes the background color of the links panel in dark mode on mobile screens. (pkgdown has some custom styles that don't adapt to the color mode change.)
=> docs(pkgdown): Fix pkgdown links in dark mode

R/navs-legacy.R, man/fragments/ex-navset_tab.Rmd, man/navset.Rd
Fixes #777
Moves the examples and screenshots into an Examples section
=> docs: Use `@section` for navset examples

R/input-switch.R
Introduced by https://github.com/rstudio/bslib/pull/709. Fixes the following error (discovered through and will fix https://rstudio.github.io/shinycoreci/results/2023/09/11/#315-bslib-input-switch)
```r
library(shiny)
library(bslib)
ui <- page_fixed(
input_switch("x", "Switch")
)
server <- function(input, output, session) {
toggle_switch("x")
}
shinyApp(ui, server)
```
```r
Error in rlang::is_string(id, n = 1) : unused argument (n = 1)
```
=> Fix use of rlang::is_string() inside of toggle_switch()

R/bs-theme-preset.R, tests/testthat/_snaps/bs-theme-preset.md
Fixes a small typo in the error message when both `preset` and `bootswatch` are provided. (Example in snapshot diff.)
=> fix(preset): Fix typo in error message

R/accordion.R, R/card.R, R/input-switch.R, R/layout.R, R/nav-items.R, R/sidebar.R, R/utils-deps.R
Closes #820. Follow up to #810.
=> Attach consolidated component dependencies to each component

R/popover.R, R/tooltip.R, man/fragments/tooltip-popover_a11y-trigger.Rmd, man/fragments/tooltip-popover_theming.Rmd, man/popover.Rd, man/tooltip.Rd
Adds a new section to tooltips and popovers on advice for using accessible triggers.
I also consolidated the repetitive parts of our documentation in to Rmd fragments so that we can have both the accessibility and theming docs in both `tooltip()` and `popover()` without literaly repeating the code in two places. This also resolved issues where the word "popover" was used in the `tooltip()` docs.
=> docs(tooltip,popover): Document trigger accessibility considerations

NEWS.md, R/sidebar.R, man/sidebar.Rd, tests/testthat/_snaps/page.md
Fixes #579
This PR improves the accessibility of the sidebar markup in three ways:
* Removes `role="main'` from the sidebar `.main` area. This is a WCAG violation, because there should only be one main landmark on the page.
* Uses `<aside>` for the sidebar, rather than `role="complimentary"`. These are functionally equivalent.
* Uses `<header>` for the sidebar title.
=> Use semantic elements in sidebar

R/sidebar.R, tests/testthat/_snaps/page.md
```r
page_sidebar(sidebar = "Side", "main")
```
=> Change `sidebar()` toggle icon back to chevron-left

NEWS.md, R/layout.R, man/layout_column_wrap.Rd, man/layout_columns.Rd, tests/testthat/test-layout.R
Supersedes #799
Addresses https://github.com/posit-dev/py-shiny/issues/732
**Breaking:** This PR makes `width` an optional argument and moves it to after the `...`. A [code search shows that most people name the `width` argument](https://github.com/search?q=language:r+layout_column_wrap&type=code), but in case they haven't we'll test to see if the first argument to `layout_column_wrap()` looks like a valid `width` value (a single numeric value or a valid CSS unit) and we'll emit a deprecation warning and use that first value as `width`.
Note: in the deprecation warning I'm assuming this breaking change will cause our next version to be v0.6.0 (in any case, we should review our deprecation warnings before the next release to make sure we have the right version in them).
Some code to try …
=> breaking(layout_column_wrap): Make `width` optional but must be named

R/value-box.R
This should cover all relevant occurrences of `0.5.2` and `deprecate_`
=> Update version in `value_box()`'s deprecation method

R/tooltip.R, man/tooltip.Rd
Related docs: https://github.com/rstudio/bslib/pull/825/files#diff-7e26871f21e46dd166aac31c26b3b59c7a956dbc64a9ed980d2b8509165ec3bbR17
=> docs: Use `a11y` arg from docs for tooltip example

DESCRIPTION, inst/builtin/bs5/shiny/ionrangeslider/_variables.scss
This reverts one small change from #764 to use Sass' `tint-color()` instead of opacity to lighten the handle color.
I think we assumed that `$component-active-bg` uses a CSS variable, but for now it directly uses `$primary`. There's an argument to be made that Bootstrap should use these CSS variables, and I think we should wait for upstream changes rather than patch this highly used variable.
=> fix(shiny-preset): Use tinted color in ionrangeslider handle color on hover

inst/themer-demo/app.R
Now that the buttons have more padding, it's easier for them to overflow their container. `layout_columns()` will prevent that
=> Use `layout_columns()` to layout buttons in themer-demo app

R/bs-dependencies.R, R/page.R, tests/testthat/_snaps/page/card.html
This reverts commit 147462a9f4e5629cfe161c5ec015390f97dde1a2 from #810, moving back to including the component deps within bslib's `page_*()` functions, but not in `bs_theme_dependencies()`.
The reason for this change is that most consumers of `bs_theme_dependencies()` (pkgdown, rmarkdown, etc.) are looking for the html dependencies for Bootstrap, not necessarily Bootstrap + bslib's components deps.
=> chore: Move component deps back to page functions

inst/builtin/bs5/shiny/_variables.scss, inst/components/scss/value_box.scss
Follow up from #902 to make two readability changes to the shiny preset and value box Sass code.
=> chore: Move around some Sass lines for readability

R/sidebar.R
Fixes a wording issue in a warning message when `max_height_mobile` is used in `sidebar()` and `open != "always"`.
```r
invisible(sidebar(max_height_mobile = 300))
#> Warning message:
#> The `max_height_mobile` argument only applies to when `open = "always"`. 
invisible(sidebar(max_height_mobile = 300))
#> Warning message:
#> The `max_height_mobile` argument only applies to the sidebar when `open = "always"`. 
```
=> chore: Fix and adjust wording in warning message

inst/themer-demo/app.R
A small change to the themer demo app to use a regular `tags$div()` for BS <5, since `layout_columns()` requires BS5+.
=> fix(themer-demo): `layout_columns()` requires BS5

R/layout.R, tests/testthat/test-layout.R
Fixes a small bug I introduced in the refactoring at the end of #931 where we didn't correctly interpret a scalar `NA` as no column spec.
```patch
layout_columns(div(class = "item")) |> format() |> cat()
-<bslib-layout-columns class="bslib-grid grid bslib-mb-spacing html-fill-item" col-widths-md data-require-bs-caller="layout_columns()" data-require-bs-version="5">
+<bslib-layout-columns class="bslib-grid grid bslib-mb-spacing html-fill-item" data-require-bs-caller="layout_columns()" data-require-bs-version="5">
<div class="bslib-grid-item bslib-gap-spacing html-fill-container">
<div class="item"></div>
</div>
</bslib-layout-columns>
```
Note that we were accidentally adding the `col-widths-md` attribute.
=> fix(layout_columns): Catch and treat `NA` as expected

R/sidebar.R
Two quick follow-ups for #943
* Fixes a typo that set `open = "desktop"` equal to `list(desktop = "open", mobile = "always")` instead of `mobile = "closed"`.
* Adds `"toggle"` to the valid choices for `open` in `toggle_sidebar()`
=> Two quick fixes for sidebar mobile/desktop options

NEWS.md, R/layout.R, R/value-box.R, man/layout_column_wrap.Rd, man/layout_columns.Rd, man/value_box.Rd
Fixes #973 #974
* Adds `min_height` to `value_box()`
* Adds `min_height` and `max_height` to `layout_columns()` and `layout_column_wrap()`
<details>
<summary>Example App</summary>
```r
library(shiny)
library(bslib)
library(ggplot2)
data(penguins, package = "palmerpenguins")
means <- colMeans(
penguins[c("bill_length_mm", "bill_length_mm", "body_mass_g")],
na.rm = TRUE
)
ui <- page_sidebar(
title = "Penguins dashboard",
sidebar = sidebar(
varSelectInput(
"color_by", "Color by",
penguins[c("species", "island", "sex")],
selected = "species"
)
),
layout_columns(
fill = FALSE,
value_box(
title = "Average bill length",
value = scales::unit_format(unit = "mm")(means[[1]]),
showcase = bsicons::bs_icon("align-bottom")
),
value_box(
title = "Average bill depth",
value = scales::unit_format(unit = …
```
=> feat: ensure min/max height args on `value_box()` and column layouts

NEWS.md, R/layout.R, tests/testthat/_snaps/layout.md
Fixes two issues with `layout_columns()`:
1. `col_widths = c(12, 6, 6)` now becomes `col_widths = breakpoints(sm = c(12, 6, 6))` where we previously used `md` as the default breakpoint. This update aligns with the intuitive expectation that `col_widths` of a single value is the column widths at all breakpoints (except mobile where we do something completely different).
2. While here I noticed that we actually _do need_ to include the `xs`-specific CSS variable when it's not the only variable being set. Without this change the `row_heights = breakpoints(xs = ..., sm = ...)` doesn't work as expected.
```r
library(shiny)
pkgload::load_all()
ui <- page_fillable(
layout_columns(
col_widths = c(12, 6, 6),
row_heights = breakpoints(
xs = c(7, 1.5, 1.5),
sm = c(70, 30)
),
card("Chart 1"), …
```
=> feat(layout_columns): Use `sm` as the default `col_widths` breakpoint

DESCRIPTION, tests/testthat/helper-fill.R, tests/testthat/test-fill.R
Bumps to require latest htmltools
Replaces #1015
=> chore: require htmltools (>= 0.5.7.9000)

inst/themer/themer.js
Correctly preview dark mode by setting `data-bs-theme` on `document.documentElement` instead of `document.body`.
=> fix(themer): Set dark mode correctly for preview

vignettes/value-boxes/index.Rmd
Inspired by #1036, this replaces the `ResizeObserver` used to adjust the plot layout in full screen mode with a simpler `bslib.card` event handler.
=> docs(value-box): Replace ResizeObserver with `bslib.card` event listener

R/page.R, tests/testthat/_snaps/page.md, tests/testthat/test-page.R
Follow up for #1057 to ensure attributes stay on the `.main` container, children are passed into the `.bslib-page-sidebar-main` container.
Not needed for `page_navbar()` where attributes and children end up in the nav panel container.
=> feat: Keep attrs on `.main` of `page_sidebar()`

NEWS.md, R/card.R, R/layout.R, tests/testthat/_snaps/layout.md
When `card_body(fillable = FALSE, ...)` we should not be adding the `bslib-gap-spacing` class to the card body container.
<details>
<summary>App Example</summary>
```r
library(shiny)
pkgload::load_all()
library(leaflet)
ui <- page_fillable(
card(
class = "text-bg-light",
card_body(
fillable = FALSE,
h3("Lehigh University"),
lorem::ipsum(3, 1:3 + 1),
actionButton("visit", "Visit School")
),
card_body(
leafletOutput("map_lehigh"),
)
)
)
server <- function(input, output, session) {
output$map_lehigh <- renderLeaflet({
lat  <- 40.60682
long <- -75.38024
name <- "Lehigh University"
leaflet() |>
addTiles() |>
setView(lng = long, lat = lat, zoom = 13) |>
addMarkers(lng = long, lat = lat, popup = name)
})
}
shinyApp(ui, server)
```
</details>
| Before | After |
|:--:|:--:|
| …
=> fix: Don't add `bslib-gap-spacing` when card body is not fillable

R/page.R
#1058 introduced a subtle issue that spliced attributes weren't being treated as arguments to `layout_sidebar()` in `page_sidebar()`.
This PR uses `rlang::exec()` to avoid that problem.
Currently, with bslib from main, the following does not work (the main content area is not white text on a purple background).
```r
library(shiny)
library(bslib)
ui <- page_sidebar(
bg = "purple",
fg = "white",
"Content here"
)
shinyApp(ui, \(...) { })
```
=> fix(page_sidebar): Use `rlang::exec()` to ensure spliced attributes are treated as arguments

_pkgdown.yml
also delete unnecessary components (follows-up to #1082) Since `search` is a proper menu item in pkgdown 2.1.0, we need to enable it manually.
=> docs: add `search` to navbar

R/page.R, tests/testthat/test-page.R
This fixes allowing trailing empty arguments in all of the page functions. This was broken in several page functions because the dots must come _after_ unnamed arguments in the calling functions.
Here's a minimal reprex that demonstrates the problematic pattern we were using:
```r
page_one <- function(...) {
bslib::page(..., "b",)
}
page_two <- function(...) {
bslib::page("b", ...)
}
as.character(page_one("a", ))
#> Error in `dots_list()`:
#> ! Argument 2 can't be empty.
as.character(page_two("a", ))
#> [1] "<body>\n  b\n  a\n</body>"
```
In reality, we're not adding content but rather we're adding an unnamed dependency object (in the place of `"b"` above).
```r
library(bslib)
x <- "test"
page(x, ) |> print(browse = FALSE)
#> <body>test</body>
page_fillable(x, ) |> print(browse = FALSE) …
```
=> fix(page): Allow empty dots in page functions

NEWS.md, inst/components/scss/sidebar.scss, inst/components/scss/value_box.scss
This closes #1104.
Before you submit a pull request, please ensure you've completed the following che.klist
> - [ ] Add unit tests in the tests/testthat directory.
I haven't done that, because I'm not sure how you're testing SCSS syntax here. Happy to do so if someone points me in the right direction.
=> add semicolons to appease a brittle parser

inst/examples-shiny/brand.yml/app.R
- feat: Add link to editor header to brand.yml structure
- chore: restore code to avoid saving if running in pkg dir
- feat: Use a download button if deployed on posit hosted products
- chore: Use dark bg color for sidebar
=> brand: Use download button in example app when deployed

NEWS.md, R/navbar_options.R, man/navbar_options.Rd
In setting up https://github.com/rstudio/shinycoreci/pull/283 – where we'll have test coverage for the default `page_navbar()` appearance with all Bootswatch themes – I realized that we need better instructions specifically for anyone using BS5 with a Bootswatch preset.
I added a new section to `?navbar_options` that walks through the process for getting the same navbar appearance as can be found in the Bootswatch docs for a theme. I also touched on the Sass variables we introduce.
https://github.com/rstudio/shinycoreci/pull/283 reveals that the changes in the default appearance are sub-optimal, but open the door for better customization that more closely follows upstream best practices – i.e. you could follow the Bootswatch or Bootstrap docs because they easily translate to …
=> docs: Discuss BS5 with Bootswatch in `?navbar_options`.

NEWS.md, R/bs-theme-layers.R, R/bs-theme-preview.R, R/files.R, R/layout.R, man/layout_columns.Rd, vignettes/any-project/index.Rmd, vignettes/dashboards/index.Rmd, vignettes/filling/index.Rmd, vignettes/sidebars/index.Rmd, vignettes/theming/index.Rmd, vignettes/value-boxes/index.Rmd
I know this is pedantic but these redundant apostrophes were quite glaring when reading the documentation.
NA as this PR doesn't add modify any code, just documentation.
NA as this PR doesn't add modify any code, just documentation.
Updated documentation has been generated.
Ran with 0 errors, 0 warnings, and 2 notes:
```
Duration: 1m 58.6s
❯ checking installed package size ... NOTE
installed size is 11.7Mb
sub-directories of 1Mb or more:
components   1.0Mb
fonts        2.4Mb
lib          5.3Mb
❯ checking for future file timestamps ... NOTE
unable to verify …
```
=> docs: Replaced "it's" denoting possesion to "its"
